### ISSUE TITLE
gitignore un-ignores

### ISSUE THREAD

**Issue by sencer** [ggreer/the_silver_searcher#837] opened 2016-02-09 19:02 UTC
`ag` won't work with simple (or complicated in some sense) `.gitignore` files, like 

````
*
!*.*
````

`git ls-files --others -i --exclude-standard` command is a better way of handling gitignore.

**Comment by Asheboy** [comment] 2016-03-10 09:47
I'm experiencing this issue too.

**Comment by balaclark** [comment] 2016-03-10 09:56
I can also confirm that this is a problem.

**Comment by ggreer** [comment] 2016-03-11 21:12
Duplicate of #168.

**Closed by ggreer** 2016-03-11 21:12 UTC
