### ISSUE TITLE
.gitignore not interpreted correctly?

### ISSUE THREAD

**Issue by bugthunk** [ggreer/the_silver_searcher#766] opened 2015-10-07 10:22 UTC
# Version
`$ ag --version
ag version 0.31.0`

# Files and contents in minimal example

```
$ cat .gitignore
*
!yes_search_this
```

```
$ cat yes_search_this
somethingthing
```

```
$ cat no_dont_search_this
something
```

# Behaviour
```
$ ag -U something
yes_search_this
1:somethingthing

no_dont_search_this
1:something
```

```
$ ag something
```
(i.e. no output from the last command)

# Expected behaviour
```
$ ag something
yes_search_this
1:somethingthing
```

**Comment by Sjlver** [comment] 2015-10-14 12:14
+1 for this. It seems that negated git ignore patterns are not interpreted correctly.

Would it make sense to re-use some code from git to ensure this is done correctly? See for example https://github.com/git/git/blob/master/Documentation/technical/api-directory-listing.txt

**Comment by jacob-terainsights** [comment] 2015-10-21 15:09
+1

**Comment by TSiege** [comment] 2015-10-21 19:33
+1
I have noticed that adding a `./` before the file name fixes it for the silver searcher, but this breaks the gitignore from actually working :confused:

**Comment by cpaulik** [comment] 2015-11-05 09:12
:+1:

**Comment by pmorch** [comment] 2015-11-08 10:00
This fits the subject: `.gitignore not interpreted correctly`, but does look like it isn't exactly the same issue. Let me know and I'll open a new issue instead:

    # ag finds something inside debian/install when run from here
    git/dist> ag BLOCK:
    debian/install/file/path/RunMySQL.pm
    35:BLOCK: More code to remove

    # but doesn't when run from here
    git/dist> cd debian/
    git/dist/debian> ag BLOCK:

    # .gitignore is setup in a way that git understands
    git/dist/debian> grep '^\/install$' .gitignore
    /install

So it seems this is another aspect of .gitignore files not being interpreted correctly. Or at least not the same way that `git` interprets them, which I'm assuming is the point.

**Comment by pmorch** [comment] 2015-11-08 10:06
Another (presumably faster) way to "resolve" this could be to document exactly what subset of `.gitignore` syntax is supported and which not. And (optionally?) issue warnings about unsupported `.gitignore` syntax.

**Comment by davidxmoody** [comment] 2015-11-10 07:50
Another example of it not quite matching the gitignore spec:

- `/node_modules/` is a valid gitignore pattern which will ignore a directory called `node_modules` only if it is at the root of the project and not if it is one or more levels deep, it is ignored by ag
- `node_modules/` is a valid gitignore pattern which will ignore a directory called `node_modules` wherever it exists in the directory structure, it *is* picked up correctly by ag

**Comment by dimroc** [comment] 2015-12-10 17:09
+1

Here is another example where all files in /src are ignored:

```
/src/*
!/src/app
```

**Comment by Snaipe** [comment] 2015-12-12 10:10
Just to add my 2 cents on the matter:

I usually make a gitignore like this:

```
*
!*.c
!*.h
```

Because I usually end up with more trash files than source files during development.

For individual, non-source files like the README, I don't bother putting them in the .gitignore and directly `git add -f` it. This is not a problem as files that are versioned bypass the .gitignore pattern.

If this does not slow down the initialization too much, I would suggest adding to the `!` pattern list individual files from `git ls-files`.

Correctness against the behaviour of `git status` should be enforced if a `.gitignore` is to be interpreted.

**Comment by ggreer** [comment] 2016-03-11 21:13
This is a duplicate of #168.

**Closed by ggreer** 2016-03-11 21:13 UTC
