### ISSUE TITLE
Ag -l prints results in color

### ISSUE THREAD

**Issue by nicolepatton66** [ggreer/the_silver_searcher#1366] opened 2020-03-18 19:32 UTC
Colorization is great, but when color is enabled the `--files-with-matches` option also prints its results in color, which makes it unusable for passing those file names into Vim for example. This coloration serves no purpose as there is nothing in the output to differentiate, and so there is only ever one color anyways. Please consider removing color from the output of this option, or at least providing a way to disable it in this particular case.

**Comment by genivia-inc** [comment] 2020-03-22 15:35
Perhaps you are looking for `--nocolor`? Works fine to remove colors from `--files-with-matches` with ag 2.2.0.

**Comment by nicolepatton66** [comment] 2020-03-23 15:22
So yes, i could of course type out `--nocolor` every time i want to use this option, but that's a pain and not an issue with grep or ack. It would be nice if this wasn't needed, which is why i'm hoping that you guys will give it some consideration. What's the benefit of yellow over white? This is the one thing that effectively prevents me from using ag full time, and i'm sure i'm not the only one who is annoyed by it.

**Comment by BurntSushi** [comment] 2020-03-23 15:27
If you pipe the results of `ag` to some other program, then `ag` should disable colors automatically. So it's not clear to me at least what the problem is here.

![ag](https://user-images.githubusercontent.com/456674/77332973-29132b00-6cf9-11ea-8211-7d8f04366bc1.png)

And running `vim $(ag parse_options --files-with-matches)` works just fine.

**Comment by nicolepatton66** [comment] 2020-03-23 15:42
Interesting. So that isn't happening for me (either case). I'm running 2.2.0 on MacOS Catalina in a bash shell. I just tried it on a linux box, and it works as described there, so this is OS specific somehow.

**Comment by genivia-inc** [comment] 2020-03-23 19:08
Piping `ag` 2.2.0 output works fine on my MacOs machine and removes colors as expected. Perhaps you've set an environment. Perhaps you're using an `ag` alias that forces color output?

**Comment by nicolepatton66** [comment] 2020-03-23 19:19
Ah yes, that was it. Removing `--color` from the alias solved the problem. Thank you, and my apologies for taking up your time.

**Comment by genivia-inc** [comment] 2020-03-23 20:08
Glad to assist. Please close this issue.

**Closed** 2020-03-23 20:10 UTC
