### ISSUE TITLE
.gitignore pattern matching is aborted on first match

### ISSUE THREAD

**Issue by RedX2501** [ggreer/the_silver_searcher#611] opened 2015-02-20 12:00 UTC
If you have a .gitignore that looks like

    *.sh
    !some_specific.sh

ag will ignore `some_specific.sh` because it matched `*.sh` to it.

ag 0.29.1 on cygwin

Here the excerpt for debug:

    DEBUG: path_start ./tools/hook/postlink filename 50_polish.sh
    DEBUG: file 50_polish.sh ignored because name matches extension sh

Here is my .gitignore:

    43: *.sh
    (...)
    70: !./tools/hook/postlink/50_polish.sh

**Comment by RedX2501** [comment] 2015-02-20 12:30
I looked into the source and the problem here seems to be the special handling of extensions.

I don't know how to fix this without impacting performance.

**Comment by RedX2501** [comment] 2015-02-21 01:25
So i have taken into fixing this.

**Comment by ggreer** [comment] 2015-02-23 09:48
This is a duplicate of #168.

**Closed by ggreer** 2015-02-23 09:48 UTC
