### ISSUE TITLE
warning during build of the silver searcher in ubuntu

### ISSUE THREAD

**Issue by cyboflash** [ggreer/the_silver_searcher#792] opened 2015-11-12 18:50 UTC
I tried building it in Ubuntu and here is what I got after executing `make`
```
$ make
  CC       src/ignore.o
  CC       src/log.o
  CC       src/options.o
  CC       src/print.o
  CC       src/print_w32.o
  CC       src/scandir.o
  CC       src/search.o
  CC       src/lang.o
  CC       src/util.o
  CC       src/decompress.o
src/decompress.c: In function ‘decompress_zlib’:
src/decompress.c:52:22: warning: cast discards ‘__attribute__((const))’ qualifier from pointer target type [-Wcast-qual]
     stream.next_in = (Bytef *)buf;
                      ^
  CC       src/main.o
  CCLD     ag
```
I'm not sure if this is significant but I though developers should be aware of it.

**Comment by ggreer** [comment] 2015-11-12 22:37
Duplicate of #662. Please search issues before creating a new one.

**Closed by ggreer** 2015-11-12 22:37 UTC
